name: Dev
variables:
  - name: host
    value: http://localhost:8000/api
    description: ""
  - name: uploader_id
    value: "1"
    description: ""
  - name: token
    value: all
    description: ""
